<?php
/**
 * DataPayload
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SERTONE REST API
 *
 * This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).
 *
 * OpenAPI spec version: 0.0.1
 * Contact: email@sertone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * DataPayload Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DataPayload implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'DataPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'dev_eui' => 'string',
        'app_eui' => 'string',
        'seq_num' => 'int',
        'last_data_received' => 'string',
        'payload' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'dev_eui' => 'devEui',
        'app_eui' => 'appEui',
        'seq_num' => 'seqNum',
        'last_data_received' => 'lastDataReceived',
        'payload' => 'payload'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'dev_eui' => 'setDevEui',
        'app_eui' => 'setAppEui',
        'seq_num' => 'setSeqNum',
        'last_data_received' => 'setLastDataReceived',
        'payload' => 'setPayload'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'dev_eui' => 'getDevEui',
        'app_eui' => 'getAppEui',
        'seq_num' => 'getSeqNum',
        'last_data_received' => 'getLastDataReceived',
        'payload' => 'getPayload'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['dev_eui'] = isset($data['dev_eui']) ? $data['dev_eui'] : null;
        $this->container['app_eui'] = isset($data['app_eui']) ? $data['app_eui'] : null;
        $this->container['seq_num'] = isset($data['seq_num']) ? $data['seq_num'] : null;
        $this->container['last_data_received'] = isset($data['last_data_received']) ? $data['last_data_received'] : null;
        $this->container['payload'] = isset($data['payload']) ? $data['payload'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets dev_eui
     * @return string
     */
    public function getDevEui()
    {
        return $this->container['dev_eui'];
    }

    /**
     * Sets dev_eui
     * @param string $dev_eui
     * @return $this
     */
    public function setDevEui($dev_eui)
    {
        $this->container['dev_eui'] = $dev_eui;

        return $this;
    }

    /**
     * Gets app_eui
     * @return string
     */
    public function getAppEui()
    {
        return $this->container['app_eui'];
    }

    /**
     * Sets app_eui
     * @param string $app_eui
     * @return $this
     */
    public function setAppEui($app_eui)
    {
        $this->container['app_eui'] = $app_eui;

        return $this;
    }

    /**
     * Gets seq_num
     * @return int
     */
    public function getSeqNum()
    {
        return $this->container['seq_num'];
    }

    /**
     * Sets seq_num
     * @param int $seq_num
     * @return $this
     */
    public function setSeqNum($seq_num)
    {
        $this->container['seq_num'] = $seq_num;

        return $this;
    }

    /**
     * Gets last_data_received
     * @return string
     */
    public function getLastDataReceived()
    {
        return $this->container['last_data_received'];
    }

    /**
     * Sets last_data_received
     * @param string $last_data_received
     * @return $this
     */
    public function setLastDataReceived($last_data_received)
    {
        $this->container['last_data_received'] = $last_data_received;

        return $this;
    }

    /**
     * Gets payload
     * @return string
     */
    public function getPayload()
    {
        return $this->container['payload'];
    }

    /**
     * Sets payload
     * @param string $payload
     * @return $this
     */
    public function setPayload($payload)
    {
        $this->container['payload'] = $payload;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
