/**
 * SERTONE REST API
 * This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).
 *
 * OpenAPI spec version: 0.0.1
 * Contact: email@sertone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Nodes', 'model/NodeInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Nodes'), require('../model/NodeInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.SertoneRestApi) {
      root.SertoneRestApi = {};
    }
    root.SertoneRestApi.NodesApi = factory(root.SertoneRestApi.ApiClient, root.SertoneRestApi.Nodes, root.SertoneRestApi.NodeInfo);
  }
}(this, function(ApiClient, Nodes, NodeInfo) {
  'use strict';

  /**
   * Nodes service.
   * @module api/NodesApi
   * @version 0.0.1
   */

  /**
   * Constructs a new NodesApi. 
   * @alias module:api/NodesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getNodesByUserId operation.
     * @callback module:api/NodesApi~getNodesByUserIdCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Nodes>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getNodesByUserId() - Gets all nodes owned by given user.
     * 
     * @param {String} userId The userId whom to get owned nodes
     * @param {module:api/NodesApi~getNodesByUserIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/Nodes>}
     */
    this.getNodesByUserId = function(userId, callback) {
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId == undefined || userId == null) {
        throw "Missing the required parameter 'userId' when calling getNodesByUserId";
      }


      var pathParams = {
        'userId': userId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['server_token', 'client_id'];
      var contentTypes = ['application/xml', 'application/json'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = [Nodes];

      return this.apiClient.callApi(
        '/users/{userId}/nodes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getNodesByUserIdAndSensorId operation.
     * @callback module:api/NodesApi~getNodesByUserIdAndSensorIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/NodeInfo} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getNodesByUserIdAndSensorId() - Gets details of given node ID for this given user.
     * 
     * @param {String} userId The userId where node will be retrieved
     * @param {String} devEui The sensorID to be retrieved
     * @param {module:api/NodesApi~getNodesByUserIdAndSensorIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/NodeInfo}
     */
    this.getNodesByUserIdAndSensorId = function(userId, devEui, callback) {
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId == undefined || userId == null) {
        throw "Missing the required parameter 'userId' when calling getNodesByUserIdAndSensorId";
      }

      // verify the required parameter 'devEui' is set
      if (devEui == undefined || devEui == null) {
        throw "Missing the required parameter 'devEui' when calling getNodesByUserIdAndSensorId";
      }


      var pathParams = {
        'userId': userId,
        'devEui': devEui
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['server_token', 'client_id'];
      var contentTypes = ['application/xml', 'application/json'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = NodeInfo;

      return this.apiClient.callApi(
        '/users/{userId}/nodes/{devEui}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
