//
// DataPayload.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class DataPayload: JSONEncodable {
    public var devEui: String?
    public var appEui: String?
    public var seqNum: Int64?
    public var lastDataReceived: String?
    public var payload: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["devEui"] = self.devEui
        nillableDictionary["appEui"] = self.appEui
        nillableDictionary["seqNum"] = self.seqNum?.encodeToJSON()
        nillableDictionary["lastDataReceived"] = self.lastDataReceived
        nillableDictionary["payload"] = self.payload
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
