//
// Gateways.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Gateways: JSONEncodable {
    public var id: Int64?
    public var owner: String?
    public var gatewayEui: String?
    /** Gateway status can be Planned, Active, Inactive, Maintenance, Deprecated */
    public var gatewayStatus: String?
    public var longitude: String?
    public var latitude: String?
    public var altitude: String?
    public var address: String?
    public var baseModel: String?
    public var city: String?
    public var concentrator: String?
    public var country: String?
    public var freqPlan: String?
    public var region: String?
    public var relCustomerUid: String?
    public var gatewayTitle: String?
    public var zipCode: String?
    public var createdOn: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["owner"] = self.owner
        nillableDictionary["gateway_eui"] = self.gatewayEui
        nillableDictionary["gateway_status"] = self.gatewayStatus
        nillableDictionary["longitude"] = self.longitude
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["altitude"] = self.altitude
        nillableDictionary["address"] = self.address
        nillableDictionary["base_model"] = self.baseModel
        nillableDictionary["city"] = self.city
        nillableDictionary["concentrator"] = self.concentrator
        nillableDictionary["country"] = self.country
        nillableDictionary["freq_plan"] = self.freqPlan
        nillableDictionary["region"] = self.region
        nillableDictionary["rel_customer_uid"] = self.relCustomerUid
        nillableDictionary["gateway_title"] = self.gatewayTitle
        nillableDictionary["zip_code"] = self.zipCode
        nillableDictionary["created_on"] = self.createdOn
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
