//
// Nodes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Nodes: JSONEncodable {
    /** Registration Type - OTAA or ABP */
    public var regType: String?
    public var devEui: String?
    public var appEui: String?
    public var appKey: String?
    public var appSKey: String?
    public var devAddr: String?
    public var nwkSKey: String?
    public var fcntUp: Int32?
    public var fcntDown: Int32?
    public var flags: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["regType"] = self.regType
        nillableDictionary["devEui"] = self.devEui
        nillableDictionary["appEui"] = self.appEui
        nillableDictionary["appKey"] = self.appKey
        nillableDictionary["appSKey"] = self.appSKey
        nillableDictionary["devAddr"] = self.devAddr
        nillableDictionary["nwkSKey"] = self.nwkSKey
        nillableDictionary["fcntUp"] = self.fcntUp?.encodeToJSON()
        nillableDictionary["fcntDown"] = self.fcntDown?.encodeToJSON()
        nillableDictionary["flags"] = self.flags
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
