//
// DataAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class DataAPI: APIBase {
    /**
     getAppDevDataPayload() - Gets payload data of given application and device.
     
     - parameter appEui: (path) The appEui where payload will be retrieved 
     - parameter devEui: (path) The devEui where payload will be retrieved 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getAppDevDataPayload(appEui appEui: String, devEui: String, completion: ((data: [DataPayload]?, error: ErrorType?) -> Void)) {
        getAppDevDataPayloadWithRequestBuilder(appEui: appEui, devEui: devEui).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     getAppDevDataPayload() - Gets payload data of given application and device.
     - GET /data/{appEui}/nodes/{devEui}
     - This can only be done by the logged in users.
     - API Key:
       - type: apiKey Authorization 
       - name: server_token
     - API Key:
       - type: apiKey ClientID 
       - name: client_id
     - examples: [{contentType=application/xml, example=<DataPayload>
  <devEui>string</devEui>
  <appEui>string</appEui>
  <seqNum>123456</seqNum>
  <lastDataReceived>string</lastDataReceived>
  <payload>string</payload>
</DataPayload>}, {contentType=application/json, example=[ {
  "lastDataReceived" : "aeiou",
  "payload" : "aeiou",
  "seqNum" : 123456789,
  "appEui" : "aeiou",
  "devEui" : "aeiou"
} ]}]
     - examples: [{contentType=application/xml, example=<DataPayload>
  <devEui>string</devEui>
  <appEui>string</appEui>
  <seqNum>123456</seqNum>
  <lastDataReceived>string</lastDataReceived>
  <payload>string</payload>
</DataPayload>}, {contentType=application/json, example=[ {
  "lastDataReceived" : "aeiou",
  "payload" : "aeiou",
  "seqNum" : 123456789,
  "appEui" : "aeiou",
  "devEui" : "aeiou"
} ]}]
     
     - parameter appEui: (path) The appEui where payload will be retrieved 
     - parameter devEui: (path) The devEui where payload will be retrieved 

     - returns: RequestBuilder<[DataPayload]> 
     */
    public class func getAppDevDataPayloadWithRequestBuilder(appEui appEui: String, devEui: String) -> RequestBuilder<[DataPayload]> {
        var path = "/data/{appEui}/nodes/{devEui}"
        path = path.stringByReplacingOccurrencesOfString("{appEui}", withString: "\(appEui)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{devEui}", withString: "\(devEui)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[DataPayload]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     getAppDevLastDataTimestamp() - Gets last data timestamp for a given application and device.
     
     - parameter appEui: (path) The appEui whom to get last timestamp 
     - parameter devEui: (path) The devEui whom to get last timestamp 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getAppDevLastDataTimestamp(appEui appEui: String, devEui: String, completion: ((data: String?, error: ErrorType?) -> Void)) {
        getAppDevLastDataTimestampWithRequestBuilder(appEui: appEui, devEui: devEui).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     getAppDevLastDataTimestamp() - Gets last data timestamp for a given application and device.
     - GET /data/{appEui}/nodes/{devEui}/timestamp
     - This can only be done by the logged in users.
     - API Key:
       - type: apiKey Authorization 
       - name: server_token
     - API Key:
       - type: apiKey ClientID 
       - name: client_id
     - examples: [{contentType=application/xml, example=string}, {contentType=application/json, example="aeiou"}]
     - examples: [{contentType=application/xml, example=string}, {contentType=application/json, example="aeiou"}]
     
     - parameter appEui: (path) The appEui whom to get last timestamp 
     - parameter devEui: (path) The devEui whom to get last timestamp 

     - returns: RequestBuilder<String> 
     */
    public class func getAppDevLastDataTimestampWithRequestBuilder(appEui appEui: String, devEui: String) -> RequestBuilder<String> {
        var path = "/data/{appEui}/nodes/{devEui}/timestamp"
        path = path.stringByReplacingOccurrencesOfString("{appEui}", withString: "\(appEui)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{devEui}", withString: "\(devEui)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     getAppDevLatestCounter() - Gets the latest counter for a given application and device.
     
     - parameter appEui: (path) The appEui whom to get last timestamp 
     - parameter devEui: (path) The devEui whom to get last timestamp 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getAppDevLatestCounter(appEui appEui: String, devEui: String, completion: ((data: Int64?, error: ErrorType?) -> Void)) {
        getAppDevLatestCounterWithRequestBuilder(appEui: appEui, devEui: devEui).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     getAppDevLatestCounter() - Gets the latest counter for a given application and device.
     - GET /data/{appEui}/nodes/{devEui}/count
     - This can only be done by the logged in users.
     - API Key:
       - type: apiKey Authorization 
       - name: server_token
     - API Key:
       - type: apiKey ClientID 
       - name: client_id
     - examples: [{contentType=application/xml, example=123456}, {contentType=application/json, example=123456789}]
     - examples: [{contentType=application/xml, example=123456}, {contentType=application/json, example=123456789}]
     
     - parameter appEui: (path) The appEui whom to get last timestamp 
     - parameter devEui: (path) The devEui whom to get last timestamp 

     - returns: RequestBuilder<Int64> 
     */
    public class func getAppDevLatestCounterWithRequestBuilder(appEui appEui: String, devEui: String) -> RequestBuilder<Int64> {
        var path = "/data/{appEui}/nodes/{devEui}/count"
        path = path.stringByReplacingOccurrencesOfString("{appEui}", withString: "\(appEui)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{devEui}", withString: "\(devEui)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Int64>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     getAppLastDataMethod() - Gets last data delivery method for a given application.
     
     - parameter appEui: (path) The appEui whom to get last timestamp 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getAppLastDataMethod(appEui appEui: String, completion: ((data: String?, error: ErrorType?) -> Void)) {
        getAppLastDataMethodWithRequestBuilder(appEui: appEui).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     getAppLastDataMethod() - Gets last data delivery method for a given application.
     - GET /data/{appEui}/method
     - This can only be done by the logged in users.
     - API Key:
       - type: apiKey Authorization 
       - name: server_token
     - API Key:
       - type: apiKey ClientID 
       - name: client_id
     - examples: [{contentType=application/xml, example=string}, {contentType=application/json, example="aeiou"}]
     - examples: [{contentType=application/xml, example=string}, {contentType=application/json, example="aeiou"}]
     
     - parameter appEui: (path) The appEui whom to get last timestamp 

     - returns: RequestBuilder<String> 
     */
    public class func getAppLastDataMethodWithRequestBuilder(appEui appEui: String) -> RequestBuilder<String> {
        var path = "/data/{appEui}/method"
        path = path.stringByReplacingOccurrencesOfString("{appEui}", withString: "\(appEui)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     getAppLastDataTimestamp() - Gets last data timestamp for a given application.
     
     - parameter appEui: (path) The appEui whom to get last timestamp 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getAppLastDataTimestamp(appEui appEui: String, completion: ((data: String?, error: ErrorType?) -> Void)) {
        getAppLastDataTimestampWithRequestBuilder(appEui: appEui).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     getAppLastDataTimestamp() - Gets last data timestamp for a given application.
     - GET /data/{appEui}/timestamp
     - This can only be done by the logged in users.
     - API Key:
       - type: apiKey Authorization 
       - name: server_token
     - API Key:
       - type: apiKey ClientID 
       - name: client_id
     - examples: [{contentType=application/xml, example=string}, {contentType=application/json, example="aeiou"}]
     - examples: [{contentType=application/xml, example=string}, {contentType=application/json, example="aeiou"}]
     
     - parameter appEui: (path) The appEui whom to get last timestamp 

     - returns: RequestBuilder<String> 
     */
    public class func getAppLastDataTimestampWithRequestBuilder(appEui appEui: String) -> RequestBuilder<String> {
        var path = "/data/{appEui}/timestamp"
        path = path.stringByReplacingOccurrencesOfString("{appEui}", withString: "\(appEui)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
