=begin
SERTONE REST API

This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).

OpenAPI spec version: 0.0.1
Contact: email@sertone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ApplicationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApplicationsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ApplicationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationsApi' do
    it 'should create an instact of ApplicationsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ApplicationsApi)
    end
  end

  # unit tests for get_applications_by_user_id
  # getApplicationsByUserId() - Gets all applications owned by given user.
  # 
  # @param user_id The userId whom to get owned applications
  # @param [Hash] opts the optional parameters
  # @return [Array<Applications>]
  describe 'get_applications_by_user_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_applications_by_user_id_and_app_id
  # getApplicationsByUserIdAndAppId() - Gets details of given application ID for this given user.
  # 
  # @param user_id The userId where application will be retrieved
  # @param app_eui The applicationId to be retrieved
  # @param [Hash] opts the optional parameters
  # @return [Applications]
  describe 'get_applications_by_user_id_and_app_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
