=begin
SERTONE REST API

This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).

OpenAPI spec version: 0.0.1
Contact: email@sertone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DataApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DataApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DataApi' do
    it 'should create an instact of DataApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DataApi)
    end
  end

  # unit tests for get_app_dev_data_payload
  # getAppDevDataPayload() - Gets payload data of given application and device.
  # This can only be done by the logged in users.
  # @param app_eui The appEui where payload will be retrieved
  # @param dev_eui The devEui where payload will be retrieved
  # @param [Hash] opts the optional parameters
  # @return [Array<DataPayload>]
  describe 'get_app_dev_data_payload test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_app_dev_last_data_timestamp
  # getAppDevLastDataTimestamp() - Gets last data timestamp for a given application and device.
  # This can only be done by the logged in users.
  # @param app_eui The appEui whom to get last timestamp
  # @param dev_eui The devEui whom to get last timestamp
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_app_dev_last_data_timestamp test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_app_dev_latest_counter
  # getAppDevLatestCounter() - Gets the latest counter for a given application and device.
  # This can only be done by the logged in users.
  # @param app_eui The appEui whom to get last timestamp
  # @param dev_eui The devEui whom to get last timestamp
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'get_app_dev_latest_counter test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_app_last_data_method
  # getAppLastDataMethod() - Gets last data delivery method for a given application.
  # This can only be done by the logged in users.
  # @param app_eui The appEui whom to get last timestamp
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_app_last_data_method test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_app_last_data_timestamp
  # getAppLastDataTimestamp() - Gets last data timestamp for a given application.
  # This can only be done by the logged in users.
  # @param app_eui The appEui whom to get last timestamp
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_app_last_data_timestamp test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
