=begin
SERTONE REST API

This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).

OpenAPI spec version: 0.0.1
Contact: email@sertone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module SwaggerClient

  class Gateways
    attr_accessor :id

    attr_accessor :owner

    attr_accessor :gateway_eui

    # Gateway status can be Planned, Active, Inactive, Maintenance, Deprecated
    attr_accessor :gateway_status

    attr_accessor :longitude

    attr_accessor :latitude

    attr_accessor :altitude

    attr_accessor :address

    attr_accessor :base_model

    attr_accessor :city

    attr_accessor :concentrator

    attr_accessor :country

    attr_accessor :freq_plan

    attr_accessor :region

    attr_accessor :rel_customer_uid

    attr_accessor :gateway_title

    attr_accessor :zip_code

    attr_accessor :created_on


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'owner' => :'owner',
        :'gateway_eui' => :'gateway_eui',
        :'gateway_status' => :'gateway_status',
        :'longitude' => :'longitude',
        :'latitude' => :'latitude',
        :'altitude' => :'altitude',
        :'address' => :'address',
        :'base_model' => :'base_model',
        :'city' => :'city',
        :'concentrator' => :'concentrator',
        :'country' => :'country',
        :'freq_plan' => :'freq_plan',
        :'region' => :'region',
        :'rel_customer_uid' => :'rel_customer_uid',
        :'gateway_title' => :'gateway_title',
        :'zip_code' => :'zip_code',
        :'created_on' => :'created_on'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'Integer',
        :'owner' => :'String',
        :'gateway_eui' => :'String',
        :'gateway_status' => :'String',
        :'longitude' => :'String',
        :'latitude' => :'String',
        :'altitude' => :'String',
        :'address' => :'String',
        :'base_model' => :'String',
        :'city' => :'String',
        :'concentrator' => :'String',
        :'country' => :'String',
        :'freq_plan' => :'String',
        :'region' => :'String',
        :'rel_customer_uid' => :'String',
        :'gateway_title' => :'String',
        :'zip_code' => :'String',
        :'created_on' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'owner')
        self.owner = attributes[:'owner']
      end

      if attributes.has_key?(:'gateway_eui')
        self.gateway_eui = attributes[:'gateway_eui']
      end

      if attributes.has_key?(:'gateway_status')
        self.gateway_status = attributes[:'gateway_status']
      end

      if attributes.has_key?(:'longitude')
        self.longitude = attributes[:'longitude']
      end

      if attributes.has_key?(:'latitude')
        self.latitude = attributes[:'latitude']
      end

      if attributes.has_key?(:'altitude')
        self.altitude = attributes[:'altitude']
      end

      if attributes.has_key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.has_key?(:'base_model')
        self.base_model = attributes[:'base_model']
      end

      if attributes.has_key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.has_key?(:'concentrator')
        self.concentrator = attributes[:'concentrator']
      end

      if attributes.has_key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.has_key?(:'freq_plan')
        self.freq_plan = attributes[:'freq_plan']
      end

      if attributes.has_key?(:'region')
        self.region = attributes[:'region']
      end

      if attributes.has_key?(:'rel_customer_uid')
        self.rel_customer_uid = attributes[:'rel_customer_uid']
      end

      if attributes.has_key?(:'gateway_title')
        self.gateway_title = attributes[:'gateway_title']
      end

      if attributes.has_key?(:'zip_code')
        self.zip_code = attributes[:'zip_code']
      end

      if attributes.has_key?(:'created_on')
        self.created_on = attributes[:'created_on']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          owner == o.owner &&
          gateway_eui == o.gateway_eui &&
          gateway_status == o.gateway_status &&
          longitude == o.longitude &&
          latitude == o.latitude &&
          altitude == o.altitude &&
          address == o.address &&
          base_model == o.base_model &&
          city == o.city &&
          concentrator == o.concentrator &&
          country == o.country &&
          freq_plan == o.freq_plan &&
          region == o.region &&
          rel_customer_uid == o.rel_customer_uid &&
          gateway_title == o.gateway_title &&
          zip_code == o.zip_code &&
          created_on == o.created_on
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, owner, gateway_eui, gateway_status, longitude, latitude, altitude, address, base_model, city, concentrator, country, freq_plan, region, rel_customer_uid, gateway_title, zip_code, created_on].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
