=begin comment

SERTONE REST API

This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).

OpenAPI spec version: 0.0.1
Contact: email@sertone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::Object::NodeInfo;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

SERTONE REST API

This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).

OpenAPI spec version: 0.0.1
Contact: email@sertone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::SwaggerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'NodeInfo',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'reg_type' => {
    	datatype => 'string',
    	base_name => 'regType',
    	description => 'Registration Type - OTAA or ABP',
    	format => '',
    	read_only => '',
    		},
    'dev_eui' => {
    	datatype => 'string',
    	base_name => 'devEui',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'app_eui' => {
    	datatype => 'string',
    	base_name => 'appEui',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'app_key' => {
    	datatype => 'string',
    	base_name => 'appKey',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'app_s_key' => {
    	datatype => 'string',
    	base_name => 'appSKey',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'dev_addr' => {
    	datatype => 'string',
    	base_name => 'devAddr',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'nwk_s_key' => {
    	datatype => 'string',
    	base_name => 'nwkSKey',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'fcnt_up' => {
    	datatype => 'int',
    	base_name => 'fcntUp',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'fcnt_down' => {
    	datatype => 'int',
    	base_name => 'fcntDown',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'flags' => {
    	datatype => 'string',
    	base_name => 'flags',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'activated' => {
    	datatype => 'boolean',
    	base_name => 'activated',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'reg_type' => 'string',
    'dev_eui' => 'string',
    'app_eui' => 'string',
    'app_key' => 'string',
    'app_s_key' => 'string',
    'dev_addr' => 'string',
    'nwk_s_key' => 'string',
    'fcnt_up' => 'int',
    'fcnt_down' => 'int',
    'flags' => 'string',
    'activated' => 'boolean'
} );

__PACKAGE__->attribute_map( {
    'reg_type' => 'regType',
    'dev_eui' => 'devEui',
    'app_eui' => 'appEui',
    'app_key' => 'appKey',
    'app_s_key' => 'appSKey',
    'dev_addr' => 'devAddr',
    'nwk_s_key' => 'nwkSKey',
    'fcnt_up' => 'fcntUp',
    'fcnt_down' => 'fcntDown',
    'flags' => 'flags',
    'activated' => 'activated'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
