/**
 * SERTONE REST API
 * This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).
 *
 * OpenAPI spec version: 0.0.1
 * Contact: email@sertone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SertoneRestApi) {
      root.SertoneRestApi = {};
    }
    root.SertoneRestApi.GatewaysStatus = factory(root.SertoneRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GatewaysStatus model module.
   * @module model/GatewaysStatus
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>GatewaysStatus</code>.
   * @alias module:model/GatewaysStatus
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>GatewaysStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GatewaysStatus} obj Optional instance to populate.
   * @return {module:model/GatewaysStatus} The populated <code>GatewaysStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('gateway_eui')) {
        obj['gateway_eui'] = ApiClient.convertToType(data['gateway_eui'], 'String');
      }
      if (data.hasOwnProperty('gateway_activity')) {
        obj['gateway_activity'] = ApiClient.convertToType(data['gateway_activity'], 'String');
      }
      if (data.hasOwnProperty('last_pull_data')) {
        obj['last_pull_data'] = ApiClient.convertToType(data['last_pull_data'], 'String');
      }
      if (data.hasOwnProperty('last_push_data')) {
        obj['last_push_data'] = ApiClient.convertToType(data['last_push_data'], 'String');
      }
      if (data.hasOwnProperty('pull_data_count')) {
        obj['pull_data_count'] = ApiClient.convertToType(data['pull_data_count'], 'String');
      }
      if (data.hasOwnProperty('push_data_count')) {
        obj['push_data_count'] = ApiClient.convertToType(data['push_data_count'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} gateway_eui
   */
  exports.prototype['gateway_eui'] = undefined;
  /**
   * Gateway activity can be Active, Inactive, Not Found
   * @member {String} gateway_activity
   */
  exports.prototype['gateway_activity'] = undefined;
  /**
   * @member {String} last_pull_data
   */
  exports.prototype['last_pull_data'] = undefined;
  /**
   * @member {String} last_push_data
   */
  exports.prototype['last_push_data'] = undefined;
  /**
   * @member {String} pull_data_count
   */
  exports.prototype['pull_data_count'] = undefined;
  /**
   * @member {String} push_data_count
   */
  exports.prototype['push_data_count'] = undefined;




  return exports;
}));


