/**
 * SERTONE REST API
 * This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).
 *
 * OpenAPI spec version: 0.0.1
 * Contact: email@sertone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GatewaysStatus', 'model/Gateways'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GatewaysStatus'), require('../model/Gateways'));
  } else {
    // Browser globals (root is window)
    if (!root.SertoneRestApi) {
      root.SertoneRestApi = {};
    }
    root.SertoneRestApi.GatewaysApi = factory(root.SertoneRestApi.ApiClient, root.SertoneRestApi.GatewaysStatus, root.SertoneRestApi.Gateways);
  }
}(this, function(ApiClient, GatewaysStatus, Gateways) {
  'use strict';

  /**
   * Gateways service.
   * @module api/GatewaysApi
   * @version 0.0.1
   */

  /**
   * Constructs a new GatewaysApi. 
   * @alias module:api/GatewaysApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getGatewayStatus operation.
     * @callback module:api/GatewaysApi~getGatewayStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GatewaysStatus} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getGatewayStatus() - Gets current status of gateway.
     * 
     * @param {String} gwEui The gatewayId to be retrieved
     * @param {module:api/GatewaysApi~getGatewayStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {module:model/GatewaysStatus}
     */
    this.getGatewayStatus = function(gwEui, callback) {
      var postBody = null;

      // verify the required parameter 'gwEui' is set
      if (gwEui == undefined || gwEui == null) {
        throw "Missing the required parameter 'gwEui' when calling getGatewayStatus";
      }


      var pathParams = {
        'gwEui': gwEui
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['server_token', 'client_id'];
      var contentTypes = ['application/xml', 'application/json'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = GatewaysStatus;

      return this.apiClient.callApi(
        '/gateways/{gwEui}/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getGatewaysByUserId operation.
     * @callback module:api/GatewaysApi~getGatewaysByUserIdCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Gateways>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getGatewaysByUserId() - Gets all gateways owned by given user.
     * 
     * @param {String} userId The userId whom to get owned gateways
     * @param {module:api/GatewaysApi~getGatewaysByUserIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {Array.<module:model/Gateways>}
     */
    this.getGatewaysByUserId = function(userId, callback) {
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId == undefined || userId == null) {
        throw "Missing the required parameter 'userId' when calling getGatewaysByUserId";
      }


      var pathParams = {
        'userId': userId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['server_token', 'client_id'];
      var contentTypes = ['application/xml', 'application/json'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = [Gateways];

      return this.apiClient.callApi(
        '/users/{userId}/gateways', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
