=begin
SERTONE REST API

This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).

OpenAPI spec version: 0.0.1
Contact: email@sertone.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::GatewaysApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GatewaysApi' do
  before do
    # run before each test
    @instance = SwaggerClient::GatewaysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GatewaysApi' do
    it 'should create an instact of GatewaysApi' do
      expect(@instance).to be_instance_of(SwaggerClient::GatewaysApi)
    end
  end

  # unit tests for get_gateway_status
  # getGatewayStatus() - Gets current status of gateway.
  # 
  # @param gw_eui The gatewayId to be retrieved
  # @param [Hash] opts the optional parameters
  # @return [GatewaysStatus]
  describe 'get_gateway_status test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_gateways_by_user_id
  # getGatewaysByUserId() - Gets all gateways owned by given user.
  # 
  # @param user_id The userId whom to get owned gateways
  # @param [Hash] opts the optional parameters
  # @return [Array<Gateways>]
  describe 'get_gateways_by_user_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
