/**
 * SERTONE REST API
 * This is the SERTONE REST API server for the  Sertone IOT Developers.  You can find out more about IOT at [http://www.sertone.com](http://www.sertone.com) or about the API on [API Reference](http://dev.sertone.com/public-rest-api).
 *
 * OpenAPI spec version: 0.0.1
 * Contact: email@sertone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.DataPayload;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataApi
 */
public class DataApiTest {

    private final DataApi api = new DataApi();

    
    /**
     * getAppDevDataPayload() - Gets payload data of given application and device.
     *
     * This can only be done by the logged in users.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAppDevDataPayloadTest() throws ApiException {
        String appEui = null;
        String devEui = null;
        // List<DataPayload> response = api.getAppDevDataPayload(appEui, devEui);

        // TODO: test validations
    }
    
    /**
     * getAppDevLastDataTimestamp() - Gets last data timestamp for a given application and device.
     *
     * This can only be done by the logged in users.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAppDevLastDataTimestampTest() throws ApiException {
        String appEui = null;
        String devEui = null;
        // String response = api.getAppDevLastDataTimestamp(appEui, devEui);

        // TODO: test validations
    }
    
    /**
     * getAppDevLatestCounter() - Gets the latest counter for a given application and device.
     *
     * This can only be done by the logged in users.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAppDevLatestCounterTest() throws ApiException {
        String appEui = null;
        String devEui = null;
        // Long response = api.getAppDevLatestCounter(appEui, devEui);

        // TODO: test validations
    }
    
    /**
     * getAppLastDataMethod() - Gets last data delivery method for a given application.
     *
     * This can only be done by the logged in users.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAppLastDataMethodTest() throws ApiException {
        String appEui = null;
        // String response = api.getAppLastDataMethod(appEui);

        // TODO: test validations
    }
    
    /**
     * getAppLastDataTimestamp() - Gets last data timestamp for a given application.
     *
     * This can only be done by the logged in users.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAppLastDataTimestampTest() throws ApiException {
        String appEui = null;
        // String response = api.getAppLastDataTimestamp(appEui);

        // TODO: test validations
    }
    
}
